config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :philosophers

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/philosopher.rb
class Philosopher < ApplicationRecord
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :users
  belongs_to :philosophers
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @philosophers = Philosopher.all
  end
end

app/controllers/philosophers_controller.rb
class PhilosophersController < ApplicationController

  def index
    @philosophers = Philosopher.all
  end

  def show
    @philosopher = Philosopher.find(params[:id])
    @reservation = Reservation.new
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def index
    @reservations = Reservation.all
  end

  def show
    @reservation = Reservation.find(params[:id])
    @philosopher = @reservation.philosopher
  end

  def new
    @reservation = Reservation.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentAPhilosopher</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </head>
  <body>
    <div class="wrapper">
      <%= render "components/navbar" %>
      <%= yield %>
      <%= render "components/footer" %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1502700807168-484a3e7889d0?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1474&q=80);">
  <div class="container">
    <h1>Book a <strong>greek philosopher</strong> to <strong>enlighten your mind</strong>!</h1>
    <a class="btn btn-flat" href="#">Apply now</a>
  </div>
</div>


<h4>Take a look at the most popular philosophers</h4>

<% @philosophers.sample(4).each do |philosopher| %>
  <div class="card-product">
    <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
    <div class="card-product-infos">
      <h2><%= link_to philosopher.name, philosopher_path(philosopher) %></h2>
      <p>Product description with <strong>relevant info</strong> only.</p>
    </div>
  </div>
<% end %>


<h4>See the available philosophers <%= link_to "all philosophers", philosophers_path %></h4>

app/views/philosophers/index.html.erb
<h4>See all available philosophers here</h4>

<% @philosophers.each do |philosopher| %>
  <%= philosopher.name %>
  <%= philosopher.age %>
<% end %>

app/views/philosophers/show.html.erb
<h2>Philosopher <%= @philosopher.name %></h2>